[mypy]
disallow_subclassing_any = True
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True
warn_unused_ignores = True
warn_return_any = True
strict_equality = True

[mypy-binance.*]
ignore_missing_imports = True

[mypy-discord.*]
ignore_missing_imports = True

[mypy-peewee.*]
ignore_missing_imports = True
